# Generated by Django 2.1.3 on 2018-11-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20181119_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vote_Count', models.IntegerField()),
                ('Sum_Of_Votes', models.IntegerField()),
                ('Alternative_Wording', models.CharField(default='', max_length=500)),
                ('Election_Id', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
