# Generated by Django 2.1.3 on 2018-11-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_alternative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternative',
            name='Sum_Of_Votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alternative',
            name='Vote_Count',
            field=models.IntegerField(default=0),
        ),
    ]
