# Generated by Django 2.1.3 on 2018-12-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_vote_vote_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='Alternative_Voted_On',
            field=models.CharField(default='', max_length=200),
        ),
    ]
