# Generated by Django 2.1.3 on 2019-01-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0008_auto_20190105_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='Election_Method',
        ),
        migrations.AddField(
            model_name='question',
            name='Election_Method',
            field=models.CharField(default='', max_length=50),
        ),
    ]
