# Generated by Django 2.1.3 on 2019-01-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0009_auto_20190119_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternative',
            name='Alternative_Id',
            field=models.IntegerField(default=0),
        ),
    ]
