# Generated by Django 2.1.3 on 2019-01-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0010_alternative_alternative_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='Alternative_Voted_On',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='Election_Method',
        ),
        migrations.AddField(
            model_name='vote',
            name='Alternative_Id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='Question_Id',
            field=models.IntegerField(default=0),
        ),
    ]
