# Generated by Django 2.1.3 on 2019-01-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0011_auto_20190123_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='Vote_Value',
            field=models.IntegerField(default='', max_length=200),
        ),
    ]
