# Generated by Django 2.1.5 on 2019-01-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0012_auto_20190123_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='Vote_Value',
            field=models.IntegerField(default=''),
        ),
    ]
