# Generated by Django 2.1.5 on 2019-02-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0013_auto_20190129_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='Active_Question',
            new_name='isActive',
        ),
        migrations.AlterField(
            model_name='election',
            name='Description',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='election',
            name='Election_Creator',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='election',
            name='Election_Id',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Election_Id',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Election_Method',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='Question_Wording',
            field=models.TextField(default=' '),
        ),
    ]
