# Generated by Django 2.1.5 on 2019-03-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0014_auto_20190228_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternative',
            name='Alternative_Wording',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='alternative',
            name='Election_Id',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='vote',
            name='Election_Id',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='vote',
            name='Vote_Owner',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='vote',
            name='Vote_Value',
            field=models.IntegerField(default=' '),
        ),
    ]
